FROM codeit/dev:latest

COPY packages/core/package.json packages/core/tsconfig.json packages/core/.npmrc packages/core/
COPY packages/api/package.json packages/api/tsconfig.json packages/api/.npmrc packages/api/

ENV WORKSPACE=packages/api
CMD ["npm", "run", "dev"]
