version: '3.8'

services:
  postgres:
    container_name: codeit_postgres
    image: postgres:13-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - db_network
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: codeit_api
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    environment:
      DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}
    networks:
      - db_network

volumes:
  postgres:

networks:
  db_network:
