version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.dev
    command: ['npm', 'run', 'start:api']
    volumes:
      - ./:/app
      - nm:/app/node_modules
    tty: true
    environment:
      NODE_ENV: development
      DATABASE_URI: ${DOCKER_DATABSE_URI}

volumes:
  nm:
