version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.dev
    command: ['npm', 'run', 'start:api']
    volumes:
      - ./:/app:z
      - nm:/app/node_modules:z
    tty: true
    environment:
      NODE_ENV: development

volumes:
  nm:
