version: '3.8'

services:
  postgres:
    container_name: codeit_postgres
    image: postgres:13-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: codeit_api
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env

volumes:
  postgres:
