FROM fullstacksjs/node:16.13-slim
COPY .eslintrc.json \
  .npmrc \
  .prettierignore \
  .prettierrc.js \
  babel.config.json \
  jest.config.js \
  jest.preset.js \
  nx.json \
  package-lock.json \
  package.json \
  tsconfig.base.json \
  tsconfig.react.json \
  workspace.json \
  ./
