#!/bin/sh
set -e

docker build --tag=codeit/dev:latest -f config/docker/base/Dockerfile.dev .
docker-compose -f ./config/docker/docker-compose.base.yml -f ./config/docker/docker-compose.dev.yml build "$@"
